name: Local tests
description: Run all tests that can run locally without connecting to external systems

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Download go modules
      shell: bash
      run: go mod download

    - name: Install executables
      shell: bash
      run: |
        go install github.com/onsi/ginkgo/v2/ginkgo
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Unit tests
      shell: bash
      run: make test

    - name: Lint
      shell: bash
      run: make lint
