name: Local tests

on:
  pull_request:
    branches:
      - main

jobs:
  local_tests:
    name: Local tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run local tests
        uses: ./.github/workflows/actions/local_tests/
